// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMenuCategories() {
  return window['go']['main']['App']['GetMenuCategories']();
}

export function GetTableActiveOrder(arg1) {
  return window['go']['main']['App']['GetTableActiveOrder'](arg1);
}

export function GetTables() {
  return window['go']['main']['App']['GetTables']();
}
