// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMenuCategories():Promise<Array<main.MenuCategory>>;

export function GetTableActiveOrder(arg1:string):Promise<main.Order>;

export function GetTables():Promise<Array<main.Table>>;
